### ISSUE TITLE
`npm install` fails on node-zopfli

### ISSUE THREAD

**Issue by hxlnt** [webhintio/webhint.io#889]
Running into some issues when running `npm install` on this repo locally (Windows 10, node v12). Looks like it fails to pull down a binary from molant/node-zoplfi then fails to build from source.

```
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/molant/node-zopfli/releases/download/v2.0.3/node-zopfli-v2.0.3-node-v72-win32-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for zopfli-node@2.0.3 and node@12.5.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: C:\Program Files (x86)\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:290:12)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```
...
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zopfli-node@2.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zopfli-node@2.0.3 install script.
```

**Comment by molant** [comment]
Haven't built the binary for node 12. Might be worth looking into another option or completely ditching zopfli. Is always a pain.

For not the workaround is for you to use node 10 😞

**Comment by hxlnt** [comment]
Let's try to switch to a newer package.
